export { default as AboutUs } from './AboutUs'
export { default as Header } from './Header'
export { default as Bolits } from './Bolits'
export { default as Footer } from './Footer'
export { default as Furniture } from './Furniture'
export { default as HowWork } from './HowWork'
export { default as LinkCalc } from './LinkCalc'
export { default as Main } from './Main'
export { default as OurWorks } from './OurWorks'
export { default as TwoKinds } from './TwoKinds'
export { default as IndOrder } from './IndOrder'
export { default as BeforeAfter } from './BeforeAfter'
export { default as MainCalc } from './MainCalc'
export { default as CalcKind } from './CalcKind'
export { default as CalcCarcass } from './CalcCarcass'
export { default as CalcCloth } from './CalcCloth'
export { default as CalcFiller } from './CalcFiller'
export { default as CalcStyle } from './CalcStyle'
export { default as Calcyc } from './Calcyc'
export { default as Modal } from './Modal'
export { default as RecreateCta } from './RecreateCta'




